# Generated by Django 3.2.25 on 2024-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
